#ifndef UBOONE_LEE_PLOT_HIST_STYLE
#define UBOONE_LEE_PLOT_HIST_STYLE

// x axis of the plot_hist breakdown plots, decided from the observation channel of the cov_input file (channel name,
// variable, nbin, low and high limits; the last bin is the overflow bin):
//   1D variables: the axis title of the variable (get_hist_var_title), the values on the axis
//   categories (multiplicity): one label per bin
//   flattened multi-differential bins ("*_bin", "*_bin_t" of get_kine_var): one segment per slice, with ticks at the bin
//   edges, the edge values below the ratio and the slice labels in the spectrum (plot_hist_bins.h, generated by
//   numucc/studies/make_hist_axes.py)
// and the channel (selection category and containment) above the spectrum.

#include "TString.h"
#include "TH1.h"
#include "TLatex.h"
#include "TLine.h"
#include "TVirtualPad.h"
#include "TObjArray.h"
#include "TObjString.h"

#include <vector>
#include <cmath>
#include <algorithm>

struct HistAxisSegment{
  int index_low;              // first bin index (x axis value) of the segment
  int nbins;                  // number of bins of the segment
  std::vector<double> edges;  // inner bin edges (nbins-1 values)
  TString label;              // slice label
  int level;                  // 0: first segment of an outer slice, 1: inner slice (triple-differential)
};

struct HistPlotStyle{
  TString xtitle;                         // x axis title
  TString description;                    // channel, above the spectrum
  TString bin_labels;                     // categories: one label per bin (comma separated, overflow bin included)
  std::vector<HistAxisSegment> segments;  // flattened multi-differential bins: one segment per slice
};

#include "WCPLEEANA/plot_hist_bins.h"

// x axis title of a 1D variable of get_kine_var (variable name if unknown)
static TString get_hist_var_title(TString var_name)
{
  if( var_name.BeginsWith("KE_muon") ) return "Reco muon kinetic energy (MeV)";
  if( var_name=="muon_costheta" ) return "Reco cos#theta_{#mu}";
  if( var_name.BeginsWith("Ehadron") ) return "Reco E_{had} (MeV)";
  if( var_name.BeginsWith("Eavail") ) return "Reco E_{avail} (MeV)";
  if( var_name.BeginsWith("kine_reco_Enu") ) return "Reco E_{#nu} (MeV)";
  if( var_name=="muon_pt" ) return "Reco muon p_{T} (MeV)";
  if( var_name=="muon_pl" ) return "Reco muon p_{L} (MeV)";
  if( var_name=="reco_Kp" ) return "Reco leading proton K_{p} (MeV)";
  if( var_name=="reco_costhetap" ) return "Reco cos#theta_{p}";
  if( var_name=="reco_costhetamup" ) return "Reco cos#theta_{#mu p}";
  if( var_name=="reco_Np" ) return "Reco proton multiplicity (K_{p} #geq 45 MeV)";
  if( var_name=="muon_spacepoints_q_med" ) return "Median charge of the muon spacepoints";
  if( var_name=="muon_spacepoints_q_sum5" ) return "Summed charge of the first 5 muon spacepoints";
  if( var_name.BeginsWith("muon_spacepoints_q_") ) {
    TString k = var_name(19, var_name.Length()-19);
    if( k.IsDigit() ) return Form("Charge of muon spacepoint %d (from the start)", k.Atoi()+1);
  }
  if( var_name=="all_veto_score" ) return "Scat0p BDT score (all_veto_score)";
  if( var_name=="VtxAct_bdt_score" ) return "Act0p BDT score (VtxAct_bdt_score)";
  return var_name;
}

// channel description: the selection category and the containment of the channel name (copy index "_<digits>" dropped)
static TString get_hist_channel_label(TString ch_name)
{
  TString prefix = "numuCC_part_bdt";
  if( !ch_name.BeginsWith(prefix) ) return ch_name;
  TString label = "#nu_{#mu}CC";
  TObjArray *tokens = TString(ch_name(prefix.Length(), ch_name.Length()-prefix.Length())).Tokenize("_");
  for(int i=0; i<tokens->GetEntries(); i++) {
    TString token = ((TObjString*)tokens->At(i))->GetString();
    if( token.IsDigit() ) continue;
    if( token=="LFCHFC" ) token = "#mu FC, hadrons FC";
    else if( token=="LFCHPC" ) token = "#mu FC, hadrons PC";
    else if( token=="LPCHFC" ) token = "#mu PC, hadrons FC";
    else if( token=="LPCHPC" ) token = "#mu PC, hadrons PC";
    else if( token=="LPCorHPC" ) token = "#mu or hadrons PC";
    label += ", " + token;
  }
  delete tokens;
  return label;
}

static HistPlotStyle get_hist_plot_style(TString ch_name, TString var_name, int nbin, double low, double high)
{
  HistPlotStyle style;
  style.description = get_hist_channel_label(ch_name);
  if( get_hist_bin_axis(var_name, nbin, style) ) return style;
  style.xtitle = get_hist_var_title(var_name);
  if( var_name=="reco_Np" && nbin>0 && std::fabs((high-low)/nbin-1)<1e-6 ) {// multiplicity: bins of 1 around integers
    for(int i=0; i<=nbin; i++) {
      int n = (int)std::lround(low + 0.5 + i);
      style.bin_labels += (i>0 ? "," : "") + (i<nbin ? TString(Form("%dp", n)) : TString(Form("#geq%dp", n)));
    }
  }
  return style;
}

// x axis labels of the style (categories, segments) below the ratio pad (pad_ratio), segment separators and slice labels
// in the spectrum (pad_main), channel description above the spectrum. h: histogram with the binning of the channel. The
// value labels of the ratio pad axes are to be switched off by the caller for categories and segments.
static void draw_hist_axis(const HistPlotStyle& style, TH1* h, TVirtualPad* pad_main, TVirtualPad* pad_ratio)
{
  int nseg = style.segments.size();

  pad_ratio->cd();
  gPad->Update();
  double xmin = gPad->GetUxmin(), xmax = gPad->GetUxmax(), ymin = gPad->GetUymin(), ymax = gPad->GetUymax();
  double left = gPad->GetLeftMargin(), right = gPad->GetRightMargin(), bot = gPad->GetBottomMargin(), top = gPad->GetTopMargin();
  auto x_ndc = [&](double x) { return left + (x-xmin)/(xmax-xmin)*(1-left-right); };

  if( style.bin_labels!="" ) {// categories: one label below each bin
    TObjArray *tokens = style.bin_labels.Tokenize(",");
    for(int ibin=0; ibin<tokens->GetEntries() && ibin<h->GetNbinsX(); ibin++) {
      TLatex *latex_bin = new TLatex();
      latex_bin->SetNDC(); latex_bin->SetTextFont(42); latex_bin->SetTextAlign(23); latex_bin->SetTextSize(0.1);
      latex_bin->DrawLatex(x_ndc(h->GetBinCenter(ibin+1)), bot-0.02, ((TObjString*)tokens->At(ibin))->GetString());
    }
    delete tokens;
  }

  // segments: ticks at the inner bin edges, edge values where there is space, separators between the segments
  double last_label = -1;
  for(int iseg=0; iseg<nseg; iseg++) {
    const HistAxisSegment& seg = style.segments.at(iseg);
    for(size_t j=0; j<seg.edges.size(); j++) {
      double x = seg.index_low + j + 1;
      TLine *tick = new TLine(x, ymin, x, ymin + 0.06*(ymax-ymin));
      tick->Draw();
      if( x_ndc(x) - last_label < 0.045 ) continue;
      TLatex *latex_edge = new TLatex();
      latex_edge->SetNDC(); latex_edge->SetTextFont(42); latex_edge->SetTextAlign(23); latex_edge->SetTextSize(0.07);
      latex_edge->DrawLatex(x_ndc(x), bot-0.02, Form("%g", seg.edges.at(j)));
      last_label = x_ndc(x);
    }
    if( iseg>0 ) {
      TLine *line_seg = new TLine();
      line_seg->SetLineColor(seg.level==0 ? kGray+2 : kGray+1); line_seg->SetLineWidth(seg.level==0 ? 2 : 1);
      if( seg.level>0 ) line_seg->SetLineStyle(kDashed);
      line_seg->DrawLineNDC(x_ndc(seg.index_low), bot, x_ndc(seg.index_low), 1-top);
      last_label = std::max(last_label, x_ndc(seg.index_low));
    }
  }
  pad_ratio->Modified();

  // spectrum: separators and slice labels (below the legend), channel description above the frame
  pad_main->cd();
  gPad->Update();
  xmin = gPad->GetUxmin(); xmax = gPad->GetUxmax();
  left = gPad->GetLeftMargin(); right = gPad->GetRightMargin(); bot = gPad->GetBottomMargin(); top = gPad->GetTopMargin();
  double y_labels = 0.70;
  for(int iseg=0; iseg<nseg; iseg++) {
    const HistAxisSegment& seg = style.segments.at(iseg);
    if( iseg>0 ) {
      TLine *line_seg = new TLine();
      line_seg->SetLineColor(seg.level==0 ? kGray+2 : kGray+1); line_seg->SetLineWidth(seg.level==0 ? 2 : 1);
      if( seg.level>0 ) line_seg->SetLineStyle(kDashed);
      line_seg->DrawLineNDC(x_ndc(seg.index_low), bot, x_ndc(seg.index_low), y_labels);
    }
    if( seg.label!="" ) {
      TLatex *latex_seg = new TLatex();
      latex_seg->SetNDC(); latex_seg->SetTextFont(42);
      double x_center = x_ndc(seg.index_low + 0.5*seg.nbins);
      if( nseg>6 ) { latex_seg->SetTextAngle(90); latex_seg->SetTextAlign(32); latex_seg->SetTextSize(nseg>20 ? 0.02 : 0.028); }
      else { latex_seg->SetTextAlign(23); latex_seg->SetTextSize(0.035); }
      latex_seg->DrawLatex(x_center, y_labels-0.01, seg.label);
    }
  }
  if( style.description!="" ) {
    TLatex *latex_desc = new TLatex();
    latex_desc->SetNDC(); latex_desc->SetTextFont(42); latex_desc->SetTextAlign(11); latex_desc->SetTextSize(0.045);
    latex_desc->DrawLatex(left, 0.935, style.description);
  }
  pad_main->Modified();
  pad_ratio->cd();
}

#endif
